### ISSUE TITLE
TypeError: promisify is not a function

### ISSUE THREAD

**Issue by ghoshnirmalya** [juliangruber/capture-phantomjs#1]
I'm getting this error whenever I run you package. Maybe it's because of the `util` package from where you are importing `promisify`. 

**N.B.**
I don't think that `promisify` is merged in the `util` package.
Re: https://github.com/defunctzombie/node-util/pull/21

**Comment by juliangruber** [comment]
`util.promisify` was added in node 8, see https://nodejs.org/api/util.html#util_util_promisify_original.

Can you upgrade to that? If not, we can use a polyfill.

**Comment by ghoshnirmalya** [comment]
Currently, I'm using `v6.10.2`. So, I guess, it's because of that!
Wouldn't it be better to mention about the Node version in the ReadMe or are you planning to add a polyfill?

**Comment by ghoshnirmalya** [comment]
I'm using `v8.6.0` and still getting this issue.
