### ISSUE TITLE
wait option is ignored

### ISSUE THREAD

**Issue by benleers** [juliangruber/capture-phantomjs#2]
I'm using node version 8.4.0, phantomjs 2.1.1 & capture-phantomjs 1.4.1.
I'm trying to create screenshots of our angularjs application. To ensure that everything is loaded, I tried to configure the timeout. As soon as all the static content is loaded, the screenshot is created (resulting in an empty screenshot).

**Comment by juliangruber** [comment]
dang, that option had the wrong name! please try again with 1.4.2, it should be working now
