### ISSUE TITLE
The "original" argument must be of type Function

### ISSUE THREAD

**Issue by Longgererer** [juliangruber/capture-phantomjs#24]
When I require capture-phantomjs,
chrome report this error:

![image](https://user-images.githubusercontent.com/40834209/77280311-eeac8c80-6cfe-11ea-9e62-0ac0d72dabfd.png)

**Comment by juliangruber** [comment]
This module won't work in the browser, as a browser can't launch phantomjs. It works in node only.

I'm going to close this, but do you want to tell me what you're trying to achieve? Maybe I can help

**Comment by Longgererer** [comment]
Oh, thank you!
Actually, I need to take a snapshot of the iframe on the front end.
Currently, I use html2canvas, but the results are often inconsistent with the style of the iframe (maybe many CSS styles are not recognized by the html2canvas).
So I tried to find some better screenshots.

**Comment by juliangruber** [comment]
ooh, right, this module won't work for that unfortunately, and I'm not aware of the best solution for this
