### ISSUE TITLE
Can I capture multiple SVG within a html selector? 

### ISSUE THREAD

**Issue by imtiaz-emu** [juliangruber/capture-phantomjs#3]
In my webpage, it contains multiple SVG under a specific `section`, like below:
```
<section id="svgs">
  <svg1> 
  <svg2>
  <svg3>
</section>
```

Is it possible to capture those 3 SVGs under the section with id `svgs`?

**Comment by juliangruber** [comment]
Currently we don't support capturing only a particular selection, but you can for sure capture a whole page containing those svgs

**Comment by imtiaz-emu** [comment]
Cool!  Is it compatible with angular 4?  
Does any of your other capturing projects support this?

**Comment by juliangruber** [comment]
It is based on an older webkit version, in case angular 4 doesn't run here check out capture-electron
