### ISSUE TITLE
Errors are ignored

### ISSUE THREAD

**Issue by innerspirit** [juliangruber/capture-phantomjs#4]
Hi, it looks like errors coming from PhantomJS are just forwarded to the screenshot output

`).then(({ stdout }) => Buffer.from(stdout, 'base64'))`

When I tried capturing an https site with a bad sslProtocol config, I ended up with an image with garbled data. No error was shown on the console so it took me a while to realize it was the error output from PhantomJS being passed as image data. I would patch it myself although it seems to require a bit of refactoring.

**Comment by juliangruber** [comment]
Hey, thanks for reporting this issue! Can you share with me a snippet where I can reproduce the SSL issue / or any other phantom error, so I can make sure I fix it properly?

**Comment by innerspirit** [comment]
Hey sorry for not responding, I just saw your message again now that you closed this. Any site with SSL errors should work. Unfortunately I couldn't find the code where I was using your project at the time.
